merge_branch:
  enable: true # Enable merge branch with comment
  branches: ['qa'] # Branches enabled to merge with comment
  users: [
    'kaduartur',
    'ernelio',
    'viniciusramosdefaria',
    'rodrigomedeirosf',
    'victor-schumacher',
    'brunasilvazup',
    'lucasdittrichzup',
    'victorschumacherzup',
    'henriquemoraeszup'
  ] # Users enabled to merge with comment

issue_project:
  enable: false # Enable issue to project when opening a new issue
