name: Test Global Commands

# TXT files used for ASSERT are located on the /testdata/gha_workflows directory.

# To help you coding your workflow tests, you can use CAT commands to show each file you will compare on the workflow window on Github.

# EXAMPLE:
#   rit init > check1.txt
#   cat check1.txt
#   cat testdata/gha_workflows/global_workflow/assert1.txt
#   diff check1.txt testdata/gha_workflows/global_workflow/assert1.txt

on:
  workflow_dispatch: # Can be triggered manually through the ACTIONS tab on Github GUI.
  push:
    paths: # Will trigger on PUSH event that update at least one of those files.
      - '**/cmd.go'
      - '**/init_test.go'
      - '**/init.go'
      - '**/metrics.go'
      - '**/metrics_test.go'
      - '**/root_test.go'
      - '**/root.go'
      - '**/set_formula_runner_test.go'
      - '**/set_formula_runner.go'
      - '**/tutorial_test.go'
      - '**/tutorial.go'
      - '**/upgrade_test.go'
      - '**/upgrade.go'
      - 'testdata/gha_workflows/global_workflow/**'
      - '**/test-global-commands.yml'
  pull_request:
    paths: # Will trigger on PULL_REQUEST event that update at least one of those files.
      - '**/cmd.go'
      - '**/init_test.go'
      - '**/init.go'
      - '**/metrics.go'
      - '**/metrics_test.go'
      - '**/root_test.go'
      - '**/root.go'
      - '**/set_formula_runner_test.go'
      - '**/set_formula_runner.go'
      - '**/tutorial_test.go'
      - '**/tutorial.go'
      - '**/upgrade_test.go'
      - '**/upgrade.go'
      - 'testdata/gha_workflows/global_workflow/**'
      - '**/test-global-commands.yml'

jobs:
  ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-linux && sudo mv ./dist/linux/rit /usr/local/bin
        - name: RIT INIT command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit init --sendMetrics="yes" --addCommons="no" --runType="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit tutorial --enabled=false
            assert_file_path: testdata/gha_workflows/global_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit tutorial --enabled=true
            assert_file_path: testdata/gha_workflows/global_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit set formula-runner --runner="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert4.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (5)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit set formula-runner --runner="docker"
            assert_file_path: testdata/gha_workflows/global_workflow/assert5.txt
            expected_result: PASSED
        - name: RIT --VERSION command (6)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit --version
            assert_file_path: testdata/gha_workflows/global_workflow/assert6.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT UPGRADE command (7)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: sudo rit upgrade
            assert_file_path: testdata/gha_workflows/global_workflow/assert7.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT METRICS command (8)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit metrics --metrics="yes"
            assert_file_path: testdata/gha_workflows/global_workflow/assert8.txt
            expected_result: PASSED
            specific_line: 1

  macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            cd $GITHUB_WORKSPACE
            make build-mac && sudo mv ./dist/darwin/rit /usr/local/bin
        - name: RIT INIT command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit init --sendMetrics="yes" --addCommons="no" --runType="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert1.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit tutorial --enabled=false
            assert_file_path: testdata/gha_workflows/global_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit tutorial --enabled=true
            assert_file_path: testdata/gha_workflows/global_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit set formula-runner --runner="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert4.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (5)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit set formula-runner --runner="docker"
            assert_file_path: testdata/gha_workflows/global_workflow/assert5.txt
            expected_result: PASSED
        - name: RIT --VERSION command (6)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: rit --version
            assert_file_path: testdata/gha_workflows/global_workflow/assert6.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT UPGRADE command (7)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: sudo rit upgrade
            assert_file_path: testdata/gha_workflows/global_workflow/assert7.txt
            expected_result: PASSED
            specific_line: 1

  windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Create binary from branch
          run: |
            choco install make
            make build-windows && move D:\a\ritchie-cli\ritchie-cli\dist\windows\rit.exe "D:\a\ritchie-cli\ritchie-cli"
            ls
        - name: RIT INIT command (1)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe init --sendMetrics="yes" --addCommons="no" --runType="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert1_win.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (2)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe tutorial --enabled=false
            assert_file_path: testdata/gha_workflows/global_workflow/assert2.txt
            expected_result: PASSED
        - name: RIT TUTORIAL command (3)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe tutorial --enabled=true
            assert_file_path: testdata/gha_workflows/global_workflow/assert3.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (4)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe set formula-runner --runner="local"
            assert_file_path: testdata/gha_workflows/global_workflow/assert4.txt
            expected_result: PASSED
        - name: RIT SET FORMULA-RUNNER command (5)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe set formula-runner --runner="docker"
            assert_file_path: testdata/gha_workflows/global_workflow/assert5.txt
            expected_result: PASSED
        - name: RIT --VERSION command (6)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe --version
            assert_file_path: testdata/gha_workflows/global_workflow/assert6.txt
            expected_result: PASSED
            specific_line: 1
        - name: RIT UPGRADE command (7)
          uses: GuillaumeFalourd/test-cli-commands-action@v1
          with:
            command_line: ./rit.exe upgrade
            assert_file_path: testdata/gha_workflows/global_workflow/assert7.txt
            expected_result: PASSED
            specific_line: 1
